### ISSUE TITLE
Incluir en el Readme los miembros del equipo

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/dede_es5c#1]
En el archivo Readme.md  del repositorio es debe crearse una sección llamada **Miembros del equipo**  en la que cada integrante realice un commit que incluya 2 cosas:

- Nombre completo
- UO

**Comment by uo277516** [comment]
Hecho 8fb28b48cd724bdab723995ad1795178e977b7f9

**Comment by uo277440** [comment]
Hecho a6f9e314b84ca284f21f9715fd6e8290af0fb808

**Comment by UO271033** [comment]
Hecho b27eee4e37cdc613a423c29ff6fb11f68920ee74
