### ISSUE TITLE
Problemas con el despliegue

### ISSUE THREAD

**Issue by UO271033** [Arquisoft/dede_es5c#117]
Tengo el siguiente error al hacer el despliegue llevo un par de semanas sin conseguir desplegar ya que cada vez me sale un error distinto
![image](https://user-images.githubusercontent.com/71436128/166471924-2741e1f8-5ed3-489e-9ab5-dd55d787c168.png)

**Comment by cidinene** [comment]
parece que no ha instalado correctamente el modulo solid-ui-react. No tengo acceso a heroku, con lo que no puedo probar lo siguiente :
  -  npm install @inrupt/solid-ui-react --force

  En caso de que no funcione lo anterior no eliminaría todo el directorio node_modules e intentaría volver a lanzar _npm ci_
Por cierto, viendo vuestro actions, recordar que el push de los packages debe ir después lanzar los test, y cuando se hace el push es cuando se debe hacer el despliegue.

**Comment by UO271033** [comment]
f1531f7995e1d7971b03446823f1ca49cd91c22c
lo acabo de probar pero tampoco funciona probare a hacer lo de borrar node_modules

**Comment by uo277516** [comment]
Hecho despliegue en Heroku, fallo de que no deja iniciar sesión con el POD

**Comment by cidinene** [comment]
Cúal sería el enlace?

**Comment by UO271033** [comment]
Lo de los tests es porque estaba haciendo pruebas y asi era mas rápido cuando terminemos de solucionar bugs lo despliego con los tests.
El enlace es este https://dede5cwebapp.herokuapp.com/

**Comment by UO271033** [comment]
394d1bc8a75358a7f1e4e48eca047dcd81ed7ebe
